In [8]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
import re
import warnings 
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.metrics import  (accuracy_score,precision_score,recall_score,f1_score,classification_report,ConfusionMatrixDisplay)

import tensorflow as tf
from tensorflow.keras.layers import(Embedding,SimpleRNN,LSTM,GRU,Bidirectional,Dense,Dropout,SpatialDropout1D)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.callbacks import (EarlyStopping,ReduceLROnPlateau,ModelCheckpoint)
import  pickle

## IMPORT DATASET

In [9]:
df1=pd.read_json("Sarcasm_Headlines_Dataset_v2.json",lines=True)

In [10]:
df1.head()

,is_sarcastic,headline,article_link
0,1,thirtysomething scientists unveil doomsday clo...,https://www.theonion.com/thirtysomething-scien...
1,0,dem rep. totally nails why congress is falling...,https://www.huffingtonpost.com/entry/donna-edw...
2,0,eat your veggies: 9 deliciously different recipes,https://www.huffingtonpost.com/entry/eat-your-...
3,1,inclement weather prevents liar from getting t...,https://local.theonion.com/inclement-weather-p...
4,1,mother comes pretty close to using word 'strea...,https://www.theonion.com/mother-comes-pretty-c...

In [12]:
df1.duplicated().sum()

np.int64(2)

In [15]:
df1["headline"].duplicated().sum()

np.int64(116)

In [17]:
df1.drop_duplicates(subset="headline",inplace=True)

In [18]:
df1.isnull().sum()

is_sarcastic    0
headline        0
article_link    0
dtype: int64

## TEXT CLEANING MINIMAL (  FOR DEEP LEARNING )

In [19]:
def clean_text(text):
    text= str(text).lower()

    #remove URL
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)

    # Remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [21]:
df1["clean_text"]=df1["headline"].apply(clean_text)

In [22]:
df1[["headline","clean_text"]].head(10)

,headline,clean_text
0,thirtysomething scientists unveil doomsday clo...,thirtysomething scientists unveil doomsday clo...
1,dem rep. totally nails why congress is falling...,dem rep. totally nails why congress is falling...
2,eat your veggies: 9 deliciously different recipes,eat your veggies: 9 deliciously different recipes
3,inclement weather prevents liar from getting t...,inclement weather prevents liar from getting t...
4,mother comes pretty close to using word 'strea...,mother comes pretty close to using word 'strea...
5,my white inheritance,my white inheritance
6,5 ways to file your taxes with less stress,5 ways to file your taxes with less stress
7,richard branson's global-warming donation near...,richard branson's global-warming donation near...
8,shadow government getting too large to meet in...,shadow government getting too large to meet in...
9,lots of parents know this scenario,lots of parents know this scenario

## DEFINE X AND Y