#### Import All Necessary Libraries

In [50]:
import pandas as pd
import numpy as np 

import matplotlib.pyplot as plt
import seaborn as sns

import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

import warnings 
warnings.filterwarnings("ignore")

#### Dataset Loading

In [51]:
df=pd.read_json("Sarcasm_Headlines_Dataset_v2.json",lines=True)

In [52]:
df.head()

,is_sarcastic,headline,article_link
0,1,thirtysomething scientists unveil doomsday clo...,https://www.theonion.com/thirtysomething-scien...
1,0,dem rep. totally nails why congress is falling...,https://www.huffingtonpost.com/entry/donna-edw...
2,0,eat your veggies: 9 deliciously different recipes,https://www.huffingtonpost.com/entry/eat-your-...
3,1,inclement weather prevents liar from getting t...,https://local.theonion.com/inclement-weather-p...
4,1,mother comes pretty close to using word 'strea...,https://www.theonion.com/mother-comes-pretty-c...

In [53]:
df.tail()

,is_sarcastic,headline,article_link
28614,1,jews to celebrate rosh hashasha or something,https://www.theonion.com/jews-to-celebrate-ros...
28615,1,internal affairs investigator disappointed con...,https://local.theonion.com/internal-affairs-in...
28616,0,the most beautiful acceptance speech this week...,https://www.huffingtonpost.com/entry/andrew-ah...
28617,1,mars probe destroyed by orbiting spielberg-gat...,https://www.theonion.com/mars-probe-destroyed-...
28618,1,dad clarifies this not a food stop,https://www.theonion.com/dad-clarifies-this-no...

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28619 entries, 0 to 28618
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   is_sarcastic  28619 non-null  int64
 1   headline      28619 non-null  object
 2   article_link  28619 non-null  object
dtypes: int64(1), object(2)
memory usage: 670.9+ KB

In [55]:
df.shape

(28619, 3)

In [56]:
df.describe()

       is_sarcastic
count  28619.000000
mean       0.476397
std        0.499451
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000

In [57]:
# missing values 
df.isnull().sum()

is_sarcastic    0
headline        0
article_link    0
dtype: int64

In [58]:
# checking duplicated values 
df.duplicated().sum()

np.int64(2)

In [59]:
# drop duplicate  values 
df=df.drop_duplicates()

In [60]:
df.duplicated().sum()

np.int64(0)

In [61]:
# check for headline duplicated

In [62]:
df["headline"].duplicated().sum()

np.int64(114)

In [63]:
duplicates = (
    df[df['headline'].duplicated(keep=False)]
    .sort_values('headline')
)

duplicates

,is_sarcastic,headline,article_link
7260,1,"'no way to prevent this,' says only nation whe...",https://www.theonion.com/no-way-to-prevent-thi...
10254,1,"'no way to prevent this,' says only nation whe...",https://www.theonion.com/no-way-to-prevent-thi...
10139,1,"'no way to prevent this,' says only nation whe...",https://www.theonion.com/no-way-to-prevent-thi...
12856,1,"'no way to prevent this,' says only nation whe...",https://www.theonion.com/no-way-to-prevent-thi...
18118,1,"'no way to prevent this,' says only nation whe...",https://www.theonion.com/no-way-to-prevent-thi...
...,...,...,...
24126,1,wolf pack fails to raise orphaned infant,https://www.theonion.com/wolf-pack-fails-to-ra...
14432,1,woman injured in hostile makeover,https://www.theonion.com/woman-injured-in-host...
7456,1,woman injured in hostile makeover,https://local.theonion.com/woman-injured-in-ho...
16249,1,zamboni crime family indicted in ice-shaving s...,https://www.theonion.com/zamboni-crime-family-...
25769,1,zamboni crime family indicted in ice-shaving s...,https://www.theonion.com/zamboni-crime-family-...

In [64]:
df = df.drop_duplicates(subset="headline", keep="first")

In [65]:
print(df["headline"].duplicated().sum())

0

In [67]:
df.columns

Index(['is_sarcastic', 'headline', 'article_link'], dtype='object')

In [70]:
df.dtypes

is_sarcastic     int64
headline        object
article_link    object
dtype: object

In [74]:
print("Unique values:",df["is_sarcastic"].unique())
print("\n")
print("Number of unique values:",df["is_sarcastic"].nunique())

Unique values: [1 0]


Number of unique values: 2

In [75]:
df["is_sarcastic"].value_counts()

is_sarcastic
0    14951
1    13552
Name: count, dtype: int64

In [78]:
# class percentage distribution

round(df["is_sarcastic"].value_counts(normalize=True)*100,2)

is_sarcastic
0    52.45
1    47.55
Name: proportion, dtype: float64

In [81]:
cd "C:\Users\Lenovo\Desktop\github projects\Capstone Project 2"

C:\Users\Lenovo\Desktop\github projects\Capstone Project 2

In [82]:
!git init

Initialized empty Git repository in C:/Users/Lenovo/Desktop/github projects/Capstone Project 2/.git/